---
title: "MultipleChoiceQuizzes"
author: "Gisela Dischinger"
date: "23 2 2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<script type="text/javascript" async
  src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.7/latest.js?config=TeX-MML-AM_CHTML">
</script>

## Eingangsquiz

<h1>Teste dich!</h1>
<main id="main">
	<form id="quiz" action="">
		<p id="intro">Wie gut kannst du Wahrscheinlichkeiten einschätzen?</p>
	</form>
</main>
	

```{css, echo=FALSE}
h1 {
	background: #f1f3f4 none repeat scroll 0 0 !important;
	padding: 1rem !important;
}

#quiz ul {
	list-style: none;
	margin: 0;
	padding: 0;
}

#quiz li {
	margin: 0;
	padding: 0;
}

#quiz label {
	display: block;
	background-color: #cae1ff;
	border: 2px solid black;
	border-radius: 0.2em;
	margin: 0.1em 0;
	padding: 1em 2em;
	text-align: start;
	max-width: 25em;
}

#quiz label:hover {
	background-color: #a4d3ee;
}

#quiz input:checked ~ label,
#quiz input:focus ~ label {
	background-color: #87cefa;
	border-color: solid black;
}

#quiz input {
	left: -9999px;
	position: absolute;
}

#quiz button:not(.startBtn) {
	display: none;
}

#quiz button,
#quiz label {
	cursor: pointer;
}
/* listing with solutions */

.question {
	font-weight: bold;
}

.correct {
	color: #0c0;
}

.wrong {
	color: #c00;
}

.correct:before {
	content: '✓';
	color: #0d0;
}

.wrong:before {
	content: '✗';
	color: #f00;
}

.correct:before,
.wrong:before {
	font: 2em bold;
	padding: 0 0.2em;
}

#scores,
#scores td,
#scores th {
	border: 1px solid black;
	border-collapse: collapse;
	text-align: center;
}

```


```{js, echo=FALSE}
// https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/from#Polyfill
// Production steps of ECMA-262, Edition 6, 22.1.2.1
if (!Array.from) {
	Array.from = (function () {
		var toStr = Object.prototype.toString;
		var isCallable = function (fn) {
			return typeof fn === 'function' || toStr.call(fn) === '[object Function]';
		};
		var toInteger = function (value) {
			var number = Number(value);
			if (isNaN(number)) {
				return 0;
			}
			if (number === 0 || !isFinite(number)) {
				return number;
			}
			return (number > 0 ? 1 : -1) * Math.floor(Math.abs(number));
		};
		var maxSafeInteger = Math.pow(2, 53) - 1;
		var toLength = function (value) {
			var len = toInteger(value);
			return Math.min(Math.max(len, 0), maxSafeInteger);
		};
		// The length property of the from method is 1.
		return function from(arrayLike /*, mapFn, thisArg */ ) {
			// 1. Let C be the this value.
			var C = this;
			// 2. Let items be ToObject(arrayLike).
			var items = Object(arrayLike);
			// 3. ReturnIfAbrupt(items).
			if (arrayLike === null) {
				throw new TypeError(
					"Array.from requires an array-like object - not null or undefined");
			}
			// 4. If mapfn is undefined, then let mapping be false.
			var mapFn = arguments.length > 1 ? arguments[1] : void undefined;
			var T;
			if (typeof mapFn !== 'undefined') {
				// 5. else
				// 5. a If IsCallable(mapfn) is false, throw a TypeError exception.
				if (!isCallable(mapFn)) {
					throw new TypeError(
						'Array.from: when provided, the second argument must be a function');
				}
				// 5. b. If thisArg was supplied, let T be thisArg; else let T be undefined.
				if (arguments.length > 2) {
					T = arguments[2];
				}
			}
			// 10. Let lenValue be Get(items, "length").
			// 11. Let len be ToLength(lenValue).
			var len = toLength(items.length);
			// 13. If IsConstructor(C) is true, then
			// 13. a. Let A be the result of calling the [[Construct]] internal method 
			// of C with an argument list containing the single item len.
			// 14. a. Else, Let A be ArrayCreate(len).
			var A = isCallable(C) ? Object(new C(len)) : new Array(len);
			// 16. Let k be 0.
			var k = 0;
			// 17. Repeat, while k < len… (also steps a - h)
			var kValue;
			while (k < len) {
				kValue = items[k];
				if (mapFn) {
					A[k] = typeof T === 'undefined' ? mapFn(kValue, k) : mapFn.call(T,
						kValue, k);
				} else {
					A[k] = kValue;
				}
				k += 1;
			}
			// 18. Let putStatus be Put(A, "length", len, true).
			A.length = len;
			// 20. Return A.
			return A;
		};
	}());
}
'use strict';
var myQuiz = {
	container: null,
	// helper function
	createElement: function (o) {
		var el, p;
		if (o && (o.tag || o.tagName)) {
			el = document.createElement(o.tag || o.tagName);
			if (o.text || o.txt) {
				var text = (o.text || o.txt)
				el.innerHTML = text;
			}
			for (p in o) {
				if (!p.match(/^t(e)?xt|tag(name)?$/i)) {
					el[p] = o[p];
				}
			}
		}
		return el;
	},
	// user interface for a quiz question
	createOptions: function () {
		var t = this,
			options = [],
			ul = document.createElement("ul");
		t.emptyContainer();
		t.intoContainer(t.createElement({
			tag: "h2",
			text: t.currentQuestion.question
			//text: "(" + t.currentQuestion.category + ") " + t.currentQuestion.question
		}));
		t.intoContainer(ul);
		// create options
		options.push(t.currentQuestion.solution);
		t.currentQuestion.falses.forEach(function (s) {
			options.push(s);
		});
		t.shuffleArray(options);
		options.forEach(function (s, i) {
			var li = document.createElement("li"),
				label = t.createElement({
					htmlFor: "a" + t.questions.length + "_" + i,
					tag: "label",
					text: s
				}),
				radio = t.createElement({
					id: "a" + t.questions.length + "_" + i,
					name: "answer",
					tag: "input",
					//type: "checkbox",
					type: "radio",
					tabindex: "0",
					value: s
				});
			ul.appendChild(li);
			li.appendChild(radio);
			li.appendChild(label);
		});
		// Hinweis für Tastatur-User
		t.intoContainer(t.createElement({
			tag: "button",
			text: "confirm choice",
			type: "submit"
		}));
	},
	currentChoices: [],
	currentQuestion: null,
	// data could be filled from an external source (JSON)
	data: [{
		<!-- category: '1', -->
		question: 'Wie berechnet man den Flächeninhalt eines Dreiecks?',
		solution: 'a ',
		falses: ['A=b+c',
			'darf man hier auch was anders',
			'tja kein tex'],
		explanation: 'Erklärung hier'
	}, {
		<!-- category: '2', -->
		question: 'Was ist wahrscheinlicher',
		solution: 'dass er das macht',
		falses: ['2', '3', '4'],
		explanation: 'Erklärung hier'
	}, {
		<!-- category: '4', -->
		question: 'Was soll ich noch fragen',
		solution: 'viel',
		falses: ['heute nichts mehr',
			'dies oder das',
			'egal, alles gleich gut'],
	}],
	emptyContainer: function () {
		var t = this;
		while (t.container.firstChild) {
			t.container.removeChild(t.container.firstChild);
		}
	},
	handleInput: function () {
		var t = this, // t points to myQuiz
			// create real array so we can use forEach
			inputs = Array.from(t.container.getElementsByTagName("input")),
			selectedSolution = "";
		// determine selection
		inputs.forEach(function (o) {
			if (o.checked) {
				selectedSolution = o.value;
			}
		});
		// process selected answer
		if (selectedSolution && t.currentQuestion) {
			t.currentChoices.push({
				a: selectedSolution,
				q: t.currentQuestion
			});
			t.play();
		}
		// accept start button
		if (!t.currentQuestion) {
			t.play();
		}
	},
	init: function () {
		var t = this;
		// here goes any code for loading data from an external source
		t.container = document.getElementById("quiz");
		if (t.data.length && t.container) {
			// use anonymous functions so in handleInput
			// "this" can point to myQuiz
			t.container.addEventListener("submit", function (ev) {
				t.handleInput();
				ev.stopPropagation();
				ev.preventDefault();
				return false;
			});
			t.container.addEventListener("mouseup", function (ev) {
				// we want to only support clicks on start buttons...
				var go = ev.target.tagName.match(/^button$/i);
				// ... and labels for radio buttons when in a game
				if (ev.target.tagName.match(/^label$/i) && t.currentQuestion) {
					go = true;
				}
				if (go) {
					window.setTimeout(function () {
						t.handleInput();
					}, 50);
					ev.stopPropagation();
					ev.preventDefault();
					return false;
				}
			});
			t.start();
		}
	},
	intoContainer: function (el, parentType) {
		var t = this,
			parent;
		if (!el) {
			return;
		}
		if (parentType) {
			parent = document.createElement(parentType);
			parent.appendChild(el);
		} else {
			parent = el;
		}
		t.container.appendChild(parent);
		return parent;
	},
	// ask next question or end quiz if none are left
	play: function () {
		var t = this,
			ol;
		// game over?
		if (!t.questions.length) {
			t.showResults();
			// offer restart
			window.setTimeout(function () {
				t.start();
			}, 50);
			return;
		}
		t.currentQuestion = t.questions.shift();
		t.createOptions();
	},
	// list with remaining quiz question objects
	questions: [],
	// list original questions and given answers and elaborate on solutions
	showResults: function () {
		var cat, ol, s, scores = {},
			t = this,
			tab, thead, tbody, tr;
		t.emptyContainer();
		// show message
		t.intoContainer(t.createElement({
			tag: "p",
			text: "Du hast alle Quizfragen beantwortet. Hier kommt die Auswertung:"
		}));
		// list questions and given answers
		ol = t.intoContainer(t.createElement({
			id: "result",
			tag: "ol"
		}));
		t.currentChoices.forEach(function (o) {
			var p, li = ol.appendChild(t.createElement({
				tag: "li"
			}));
			// list original question
			li.appendChild(t.createElement({
				className: "question",
				tag: "p",
				text: o.q.question
				<!-- text: "(" + o.q.category + ") " + o.q.question -->
			}));
			// list given answer
			p = li.appendChild(t.createElement({
				tag: "p",
				text: "Deine Antwort: "
			}));
			p.appendChild(t.createElement({
				className: (o.q.solution == o.a ? "correct" : "wrong"),
				tag: "em",
				text: o.a
			}));
			// wrong answer?
			if (o.q.solution != o.a) {
				p = li.appendChild(t.createElement({
					tag: "p",
					text: "Die richtige Antwort wäre gewesen: "
				}));
				p.appendChild(t.createElement({
					tag: "em",
					text: o.q.solution
				}));
			}
			// elaborate on solution?
			if (o.q.explanation) {
				p = li.appendChild(t.createElement({
					tag: "p",
					text: "Erläuterung: "
				}));
				p.appendChild(t.createElement({
					tag: "em",
					text: o.q.explanation
				}));
			}
		});
		// display a kind of percentual score over the categories
		cat = [];
		t.currentChoices.forEach(function (o) {
			if (!cat.includes(o.q.category)) {
				cat.push(o.q.category);
			}
		});
		cat.sort();
		cat.forEach(function (c) {
			var correct = 0,
				num = 0;
			t.currentChoices.forEach(function (o) {
				if (o.q.category == c) {
					num++;
					if (o.q.solution == o.a) {
						correct++;
					}
				}
			});
			scores[c] = Math.floor(100 * correct / num) + "%";
		});
		tab = t.intoContainer(t.createElement({
			id: "scores",
			tag: "table"
		}));
		<!-- tab.appendChild(t.createElement({ -->
		<!-- 	tag: "caption", -->
		<!-- 	text: "Übersicht nach Kategorien" -->
		<!-- })) -->
		<!-- thead = tab.appendChild(t.createElement({ -->
		<!-- 	tag: "thead" -->
		<!-- })) -->
		<!-- tr = thead.appendChild(t.createElement({ -->
		<!-- 	tag: "tr" -->
		<!-- })) -->
		<!-- for (s in scores) { -->
		<!-- 	tr.appendChild(t.createElement({ -->
		<!-- 		tag: "th", -->
		<!-- 		text: s -->
		<!-- 	})); -->
		<!-- } -->
		<!-- tbody = tab.appendChild(t.createElement({ -->
		<!-- 	tag: "tbody" -->
		<!-- })) -->
		<!-- tr = tbody.appendChild(t.createElement({ -->
		<!-- 	tag: "tr" -->
		<!-- })) -->
		<!-- for (s in scores) { -->
		<!-- 	tr.appendChild(t.createElement({ -->
		<!-- 		tag: "td", -->
		<!-- 		text: scores[s] -->
		<!-- 	})); -->
		<!-- } -->
		// show message
		t.intoContainer(t.createElement({
			tag: "p",
			text: "Nochmal?"
		}));
	},
	// helper function: shuffle array (adapted from http://javascript.jstruebig.de/javascript/69)
	shuffleArray: function (a) {
		var i = a.length;
		while (i >= 2) {
			var zi = Math.floor(Math.random() * i);
			var t = a[zi];
			a[zi] = a[--i];
			a[i] = t;
		}
		// no return argument since the array has been
		// handed over as a reference and not a copy!
	},
	// start quiz with a start button
	start: function () {
		var t = this;
		// fill list of remaining quiz questions
		t.questions = [];
		t.data.forEach(function (o) {
			t.questions.push(o);
		});
		t.shuffleArray(t.questions);
		t.currentChoices = [];
		t.currentQuestion = null;
		// install start button
		t.intoContainer(t.createElement({
			className: "startBtn",
			tag: "button",
			text: "Los geht's!"
		}), "p");
	}
};
document.addEventListener("DOMContentLoaded", function () {
	myQuiz.init();
});


```


## Wie sieht es damit aus?

<form id="test">
<table border="1" cellspacing="0" cellpadding="5">
<tr>
<td>$U=2\pi r$ - Was wird mit dieser Formel berechnet?</td>
<td>
<input id="q1" maxlength="30" name="q1" size="30" type="text" /></td>
</tr>
<tr>
<td>Der Durchmesser ist 5 mal der Radius.</td>
<td>
<input name="q2" type="radio" value="true" />
        True <br>
<input name="q2" type="radio" value="false" />
        False</td>
</tr>
<tr>
<td>Wie berechnet man die Fläche des Dreiecks?</td>
<td>
<input name="q3" type="radio" value="d1" />
      $a \cdot b$ <br>
<input name="q3" type="radio" value="d2" />
      $42$ <br>
<input name="q3" type="radio" value="d3" />
      $\sqrt{g}$ <br>
<input name="q3" type="radio" value="d4" />
      $A = {1 \over 2} gh$ <br>
<input name="q3" type="radio" value="keine" />
      Keine der oben genannten Lösungen ist richtig</td>
</tr>
<tr>
<td width="30%">Multipliziere aus. $(a+b)^2$ [Es können mehrer Antworten richtig sein.]</td>
<td>
<input id="q4" name="q4" type="checkbox" value="1" />
        $a^2+2ab+b^2$ <br>
<input id="q4" name="q4" type="checkbox" value="2" />
        $3 \over 6$ <br>
<input id="q4" name="q4" type="checkbox" value="3" />
        $89$ <br>
<input id="q4" name="q4" type="checkbox" value="4" />
        $A=\pi \cdot r^2$</td>
</tr>
<tr>
<td>Hans ist vier Mal so alt wie seine Schwester</td>
<td>
<select id="q5" name="q5">
        <option value="t1"> </option>
        <option value="t2">Hans kann alles</option>
        <option value="t3">$7$</option>
        <option value="t4">$4h=s$</option>
        <option value="t5">Abrakadabra</option>
      </select></td>
</tr>
</table>
<input onclick="gradeTest()" name="submit" type="button" value="Stimmts?"/>
<br>
<br>
Du hast <span id="ergebnis"> noch keine </span> von <span id="anzahlFragen"> all den </span> Aufgaben richtig gelöst!
</form>

 
```{js, echo=FALSE}

function gradeTest() {
   //variables with global implications
   var totalQuestions = 5;
   var correctAnswers = 0;
   var alertText;
   var i;
   
   var a1 = document.getElementById('q1').value.toLowerCase();
   if(a1 == 'Kreisumfang') {
      correctAnswers++;
   }

   var a2 = document.getElementsByName('q2');
   for(i = 0; i < a2.length; i++) {
      if(a2[i].checked) {
         if(a2[i].value == 'true') {
            correctAnswers++;
            break;
         }
      }
   }
   
   var a3 = document.getElementsByName('q3');
   for(i = 0; i < a3.length; i++) {
      if(a3[i].checked) {
         if(a3[i].value == 'augusta') {
            correctAnswers++;
            break;
         }
      }
   }
   
   var a4 = document.getElementsByName('q4');
   var a4answers = new Array();
   var a4right = new Array('pig','cow');
   var a4bool = true;
 
   for(i = 0; i < a4.length; i++) {
      if(a4[i].checked) {
         a4answers.push(a4[i].value);
      }
   }
   a4answers.sort();
   a4right.sort();
   if(a4answers.length == a4right.length) {
      for(i = 0; i < a4answers.length; i++) {
         if(a4answers[i] != a4right[i]) {
            a4bool = false;
            break;
         }
      }
   }
   else {
      a4bool = false;
   }
   if(a4bool == true) {
      correctAnswers++;
   }
   
  var q5 = document.getElementById('q5');
   if(q5.selectedIndex == 3) {
      correctAnswers++;
   }
   if(correctAnswers == totalQuestions) {
      alertText = "Alles richtig! Bestens!";
   }
   else {
      alertText = "Du hast " + correctAnswers + " von " + totalQuestions + " Antworten richtig!";
   }
   document.getElementById('ergebnis').innerHTML = correctAnswers;
   document.getElementById('anzahlFragen').innerHTML = totalQuestions;
   <!-- alert(alertText); -->
}




```

## Und das?

<fieldset id="question1">
    <legend>Which are fruit?</legend>
    <label><INPUT TYPE="checkbox" NAME="input" VALUE="wrong">tomatoes<BR></label>
    <label><INPUT TYPE="checkbox" NAME="input" VALUE="wrong">cucumber<BR></label>
    <label><INPUT TYPE="checkbox" NAME="input" VALUE="right">apples<BR></label>
    <label><INPUT TYPE="checkbox" NAME="input" VALUE="wrong">onion<BR></label>
    <label><INPUT TYPE="checkbox" NAME="input" VALUE="right">bananas<BR></label>
</fieldset>
<input type="button" id="answer" value="Stimmts?">

```{js, echo=FALSE}

document.getElementById("answer").onclick = validate;

function validate() {
    var checkboxes = document.getElementsByName("input");
    var checkboxChecked = []; 

    for(var i = 0; i < checkboxes.length; i++) {
        if(checkboxes[i].checked && (checkboxes[i].value === "right")) {
            checkboxChecked.push(checkboxes[i]);
        }
        if(checkboxes[i].value == "wrong" && checkboxes[i].checked == true) {
              right = false;
            }
    }

    if(checkboxChecked.length === 2) {
        alert("Richtig!");
    } 
    else {
        alert("Leider falsch!");
    }
}

```

## Wie siehts denn damit aus?

<html>
<head>
<script type="text/javascript">

function rechnen() {
  if(document.Formular.Liter.value == "") {
    alert("Es muss eine Mengenangabe für Liter vorhanden sein...");
    document.Formular.Liter.focus();
    return false;
  }
  document.Formular.Liter.value = Number(document.Formular.Liter.value.replace(/,/,"."));
  var Gramm = (document.Formular.Liter.value * 60).toFixed(2);
  var Ergebnis = "Es werden " + Gramm;
  Ergebnis += " Gramm Zitronensäuregranulat benötigt um die gewünschte Menge Entkalkerlösung anzumischen.";
  document.getElementById('ergebnis').innerHTML = Ergebnis;
}

function ErgebnisWeg() {
  var NochNix = "F&uuml;r das Ergebnis bitte auf Berechnen klicken...";
  document.getElementById('ergebnis').innerHTML = NochNix;
}

</script>
</head>
<body bgcolor="#d3b96c">
<form action="" name="Formular">
<br/>
<br/>
<br/>
Wieviel Gramm Zitronensäuregranulat benötige ich, um
<input type="text" size="4" name="Liter" onfocus="ErgebnisWeg()"/>
Liter fertige Entkalkerlösung (6%) herzustellen?
<br/>
<br/>
<aling="center" _moz-userdefined="">
<input type="button" onclick="rechnen()" value="Berechnen"/>
</aling="center">
<br/>
<br/>
<span id="ergebnis">F&uuml;r das Ergebnis bitte auf Berechnen klicken...</span>
</form>
</body>
</html>